name = "Kobold Kingdoms"
author = "Faer-Anne"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89e2889bb548c763e855bbf734dc21f20324ec6a27f006f6d5307188cd969df5"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
