name = "Kobold Kingdoms"
author = "Faer-Anne"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c106e275b8756b2ddffe09349bb3de70386f528f03644e31ed25b6636ffc6350"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
